[2013-08-01 20:33:11,885](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 20:33:42,255](DEBUG)__main__ : 192.168.0.55
[2013-08-01 20:33:42,255](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
[2013-08-01 20:33:42,295](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 20:33:42] "GET / HTTP/1.1" 500 -
[2013-08-01 20:35:21,475](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 20:35:27,709](DEBUG)__main__ : 192.168.0.55
[2013-08-01 20:35:27,710](DEBUG)__main__ : 192.168.0.55
[2013-08-01 20:35:27,711](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
[2013-08-01 20:35:27,734](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 20:35:27] "GET / HTTP/1.1" 500 -
[2013-08-01 21:13:00,912](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:13:04,995](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:13:04,996](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 72, in index
    token_info = get_token(app.config['OPSTACK_IP'])
  File "iaasapi.py", line 43, in get_token
    "url": _host_ip + ':35357',
NameError: global name '_host_ip' is not defined
[2013-08-01 21:13:05,039](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:13:05] "GET / HTTP/1.1" 500 -
[2013-08-01 21:15:10,878](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:15:14,566](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:15:14,724](DEBUG)__main__ : (u'9d69dd45f864491bbcc2fa0ccbaa2675', ParseResult(scheme=u'http', netloc=u'192.168.0.55:8774', path=u'/v2/e6442e3d73cc4a848d5acb44b618c144', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:35357', path=u'/v2.0', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:5000', path=u'/v2.0', params='', query='', fragment=''))
[2013-08-01 21:15:14,726](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1563, in make_response
    rv, status, headers = rv + (None,) * (3 - len(rv))
ValueError: too many values to unpack
[2013-08-01 21:15:14,745](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:15:14] "GET / HTTP/1.1" 500 -
[2013-08-01 21:24:36,485](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:24:49,177](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:24:49,289](DEBUG)__main__ : (u'5406f45639b047aea9f2ac20d26506ea', ParseResult(scheme=u'http', netloc=u'192.168.0.55:8774', path=u'/v2/e6442e3d73cc4a848d5acb44b618c144', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:35357', path=u'/v2.0', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:5000', path=u'/v2.0', params='', query='', fragment=''))
[2013-08-01 21:24:49,290](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1563, in make_response
    rv, status, headers = rv + (None,) * (3 - len(rv))
ValueError: too many values to unpack
[2013-08-01 21:24:49,305](INFO)werkzeug : 127.0.0.1 - - [01/Aug/2013 21:24:49] "GET / HTTP/1.1" 500 -
[2013-08-01 21:29:29,616](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:29:32,662](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:29:33,036](DEBUG)__main__ : (u'd446f15dc4d34799864143c702577691', ParseResult(scheme=u'http', netloc=u'192.168.0.55:8774', path=u'/v2/e6442e3d73cc4a848d5acb44b618c144', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:35357', path=u'/v2.0', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:5000', path=u'/v2.0', params='', query='', fragment=''))
[2013-08-01 21:29:33,038](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:29:33] "GET / HTTP/1.1" 200 -
[2013-08-01 21:30:13,699](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:30:15,551](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:30:15,683](DEBUG)__main__ : (u'91e0c5844fd74205af7b272499e918d4', ParseResult(scheme=u'http', netloc=u'192.168.0.55:8774', path=u'/v2/e6442e3d73cc4a848d5acb44b618c144', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:35357', path=u'/v2.0', params='', query='', fragment=''), ParseResult(scheme=u'http', netloc=u'192.168.0.55:5000', path=u'/v2.0', params='', query='', fragment=''))
[2013-08-01 21:30:15,684](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:30:15] "GET / HTTP/1.1" 200 -
[2013-08-01 21:32:18,393](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:32:24,950](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:32:24,968](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:32:24] "GET /get_token HTTP/1.1" 404 -
[2013-08-01 21:32:27,333](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:32:27,453](ERROR)__main__ : Exception on /get_tokens [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1563, in make_response
    rv, status, headers = rv + (None,) * (3 - len(rv))
ValueError: too many values to unpack
[2013-08-01 21:32:27,455](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:32:27] "GET /get_tokens HTTP/1.1" 500 -
[2013-08-01 21:33:15,374](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:33:18,378](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:33:18,502](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:33:18] "GET /get_tokens HTTP/1.1" 200 -
[2013-08-01 21:47:05,525](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:47:08,513](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:47:08,551](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:47:08] "GET /get_tokens HTTP/1.1" 404 -
[2013-08-01 21:47:12,589](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:47:12,718](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:47:12] "GET /get_token HTTP/1.1" 200 -
[2013-08-01 21:51:20,241](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 21:51:23,288](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:51:23,427](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:51:23] "GET /get_token HTTP/1.1" 200 -
[2013-08-01 21:51:36,413](DEBUG)__main__ : 192.168.0.55
[2013-08-01 21:51:36,414](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 21:51:36,414](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 140, in index
    {'token': g.token, 'nova': g.nova_url, 'keyA': g.keystone_adminurl,
  File "/usr/lib/python2.6/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'token'
[2013-08-01 21:51:36,464](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 21:51:36] "GET / HTTP/1.1" 500 -
[2013-08-01 22:01:47,667](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:01:52,014](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:01:52,015](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 138, in index
    'keyP': g.keystone_public})
  File "/usr/lib/python2.6/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'keystone_public'
[2013-08-01 22:01:52,041](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:01:52] "GET / HTTP/1.1" 500 -
[2013-08-01 22:02:14,579](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:02:17,308](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:02:17,308](DEBUG)__main__ : token: 83ffd0044fb14bbb9ec554840f8f7fa9, nova: ParseResult(scheme=u'http', netloc=u'192.168.0.55:8774', path=u'/v2/e6442e3d73cc4a848d5acb44b618c144', params='', query='', fragment=''), keystoneA: ParseResult(scheme=u'http', netloc=u'192.168.0.55:35357', path=u'/v2.0', params='', query='', fragment=''), keystoneP: ParseResult(scheme=u'http', netloc=u'192.168.0.55:5000', path=u'/v2.0', params='', query='', fragment='')
[2013-08-01 22:02:17,310](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:02:17,311](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:02:17] "GET / HTTP/1.1" 200 -
[2013-08-01 22:34:30,115](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:34:34,907](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:34:34,907](DEBUG)__main__ : token: b1cb3e680ff145b59cf59e5b06157a8a, nova: 192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144
[2013-08-01 22:34:34,908](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:34:34,909](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:34:34] "GET / HTTP/1.1" 200 -
[2013-08-01 22:38:27,426](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:38:29,537](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:38:29,537](DEBUG)__main__ : token: c2e499b4ecf3419aab452f6d18577859, nova: /v2/e6442e3d73cc4a848d5acb44b618c144
[2013-08-01 22:38:29,537](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-01 22:38:29,538](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:38:29] "GET / HTTP/1.1" 200 -
[2013-08-01 22:42:17,828](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:42:27,241](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:42:27] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-01 22:43:06,309](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:43:09,157](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:43:09] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-01 22:43:48,203](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:43:50,596](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:43:50] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-01 22:44:53,838](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:44:56,932](DEBUG)__main__ : start get quota
[2013-08-01 22:44:56,980](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:44:56] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-01 22:45:55,206](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:46:02,780](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:46:02] "GET /get_quota/?e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-01 22:46:06,038](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:46:06] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-01 22:51:29,120](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:51:29] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-01 22:51:31,905](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-01 22:51:33,165](DEBUG)__main__ : start get quota
[2013-08-01 22:51:33,208](INFO)werkzeug : 192.168.81.1 - - [01/Aug/2013 22:51:33] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-07 19:02:49,649](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 19:02:59,281](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 19:02:59,281](DEBUG)__main__ : token: 96b037fb36554a8ea19723dfaf4e0f33, nova: /v2/e6442e3d73cc4a848d5acb44b618c144
[2013-08-07 19:02:59,282](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 19:02:59,283](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:02:59] "GET / HTTP/1.1" 200 -
[2013-08-07 19:02:59,459](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:02:59] "GET /favicon.ico HTTP/1.1" 404 -
[2013-08-07 19:02:59,573](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:02:59] "GET /favicon.ico HTTP/1.1" 404 -
[2013-08-07 19:04:51,040](DEBUG)__main__ : start get quota
[2013-08-07 19:04:51,101](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:04:51] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-07 19:21:14,956](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:21:14] "GET /get_images HTTP/1.1" 404 -
[2013-08-07 19:23:37,754](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:23:37] "GET /get_images HTTP/1.1" 404 -
[2013-08-07 19:25:12,793](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 19:25:16,259](DEBUG)__main__ : {u'flag': u'getImages', u'data': {u'images': [{u'status': u'SAVING', u'updated': u'2013-08-08T02:17:35Z', u'name': u'yqy-ceshi_WINDOWS', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/a0b94405-4592-4309-ade4-efe3aaf30e5e', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/a0b94405-4592-4309-ade4-efe3aaf30e5e', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/a0b94405-4592-4309-ade4-efe3aaf30e5e', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-08T02:17:35Z', u'minDisk': 0, u'server': {u'id': u'5ad756b6-5c00-42fa-9af2-134836b3ee6c', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/5ad756b6-5c00-42fa-9af2-134836b3ee6c', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/5ad756b6-5c00-42fa-9af2-134836b3ee6c', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'a0b94405-4592-4309-ade4-efe3aaf30e5e', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'5ad756b6-5c00-42fa-9af2-134836b3ee6c', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'SAVING', u'updated': u'2013-08-08T02:00:10Z', u'name': u'277-1375927208233-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/19a716d4-9060-4236-aa45-7f583d0f3035', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/19a716d4-9060-4236-aa45-7f583d0f3035', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/19a716d4-9060-4236-aa45-7f583d0f3035', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-08T02:00:10Z', u'minDisk': 0, u'server': {u'id': u'39670ddf-f9cc-4689-8cea-f4d44b76124d', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/39670ddf-f9cc-4689-8cea-f4d44b76124d', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/39670ddf-f9cc-4689-8cea-f4d44b76124d', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'19a716d4-9060-4236-aa45-7f583d0f3035', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'39670ddf-f9cc-4689-8cea-f4d44b76124d', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'SAVING', u'updated': u'2013-08-08T02:00:09Z', u'name': u'275-1375927206576-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/ec248073-9219-4b63-8b5d-2fdd271674f0', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/ec248073-9219-4b63-8b5d-2fdd271674f0', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/ec248073-9219-4b63-8b5d-2fdd271674f0', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-08T02:00:09Z', u'minDisk': 0, u'server': {u'id': u'a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'ec248073-9219-4b63-8b5d-2fdd271674f0', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'SAVING', u'updated': u'2013-08-08T02:00:07Z', u'name': u'273-1375927204037-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/7fb865d2-3945-4ff1-a72e-e7280be02f24', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/7fb865d2-3945-4ff1-a72e-e7280be02f24', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/7fb865d2-3945-4ff1-a72e-e7280be02f24', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-08T02:00:07Z', u'minDisk': 0, u'server': {u'id': u'fb209de9-59d1-4e18-a951-4db2802ced23', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/fb209de9-59d1-4e18-a951-4db2802ced23', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/fb209de9-59d1-4e18-a951-4db2802ced23', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'7fb865d2-3945-4ff1-a72e-e7280be02f24', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'fb209de9-59d1-4e18-a951-4db2802ced23', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'SAVING', u'updated': u'2013-08-08T02:00:04Z', u'name': u'272-1375927201726-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/0b12b933-733a-4a24-ba79-3e931c182d36', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/0b12b933-733a-4a24-ba79-3e931c182d36', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/0b12b933-733a-4a24-ba79-3e931c182d36', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-08T02:00:04Z', u'minDisk': 0, u'server': {u'id': u'39038bbd-524e-46e2-8058-1833eeb44e3a', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/39038bbd-524e-46e2-8058-1833eeb44e3a', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/39038bbd-524e-46e2-8058-1833eeb44e3a', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'0b12b933-733a-4a24-ba79-3e931c182d36', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'39038bbd-524e-46e2-8058-1833eeb44e3a', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'SAVING', u'updated': u'2013-08-08T02:00:02Z', u'name': u'263-1375927200039-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/d2b96ad8-edf6-4a46-94c6-b7c9cd5b9441', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/d2b96ad8-edf6-4a46-94c6-b7c9cd5b9441', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/d2b96ad8-edf6-4a46-94c6-b7c9cd5b9441', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-08T02:00:02Z', u'minDisk': 0, u'server': {u'id': u'5a53a4d2-4be8-43ea-8620-767372633962', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/5a53a4d2-4be8-43ea-8620-767372633962', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/5a53a4d2-4be8-43ea-8620-767372633962', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'd2b96ad8-edf6-4a46-94c6-b7c9cd5b9441', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'5a53a4d2-4be8-43ea-8620-767372633962', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T09:50:30Z', u'name': u'272-1375866002059-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/134fdbaa-b44f-40ba-a035-78a70a57509c', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/134fdbaa-b44f-40ba-a035-78a70a57509c', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/134fdbaa-b44f-40ba-a035-78a70a57509c', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T09:00:04Z', u'minDisk': 0, u'server': {u'id': u'39038bbd-524e-46e2-8058-1833eeb44e3a', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/39038bbd-524e-46e2-8058-1833eeb44e3a', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/39038bbd-524e-46e2-8058-1833eeb44e3a', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'134fdbaa-b44f-40ba-a035-78a70a57509c', u'metadata': {u'instance_uuid': u'39038bbd-524e-46e2-8058-1833eeb44e3a', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T09:59:50Z', u'name': u'263-1375866000055-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/50dc78e4-c25c-4f35-bb69-28982929af53', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/50dc78e4-c25c-4f35-bb69-28982929af53', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/50dc78e4-c25c-4f35-bb69-28982929af53', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T09:00:02Z', u'minDisk': 0, u'server': {u'id': u'5a53a4d2-4be8-43ea-8620-767372633962', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/5a53a4d2-4be8-43ea-8620-767372633962', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/5a53a4d2-4be8-43ea-8620-767372633962', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'50dc78e4-c25c-4f35-bb69-28982929af53', u'metadata': {u'instance_uuid': u'5a53a4d2-4be8-43ea-8620-767372633962', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T10:40:29Z', u'name': u'lhypaas', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/02e22c88-dca9-469a-bc83-7fc72695956d', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/02e22c88-dca9-469a-bc83-7fc72695956d', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/02e22c88-dca9-469a-bc83-7fc72695956d', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T08:38:28Z', u'minDisk': 0, u'server': {u'id': u'1893e092-f644-4232-b83f-e8efecef88cd', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/1893e092-f644-4232-b83f-e8efecef88cd', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/1893e092-f644-4232-b83f-e8efecef88cd', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'02e22c88-dca9-469a-bc83-7fc72695956d', u'metadata': {u'instance_uuid': u'1893e092-f644-4232-b83f-e8efecef88cd', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T07:45:06Z', u'name': u'263-1375858860123-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/8aa10089-785c-45fe-94e6-96538a836672', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/8aa10089-785c-45fe-94e6-96538a836672', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/8aa10089-785c-45fe-94e6-96538a836672', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T07:01:02Z', u'minDisk': 0, u'server': {u'id': u'5a53a4d2-4be8-43ea-8620-767372633962', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/5a53a4d2-4be8-43ea-8620-767372633962', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/5a53a4d2-4be8-43ea-8620-767372633962', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'8aa10089-785c-45fe-94e6-96538a836672', u'metadata': {u'instance_uuid': u'5a53a4d2-4be8-43ea-8620-767372633962', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T07:52:30Z', u'name': u'275-1375858803706-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/02aa623f-a023-419a-9b41-19a80d8e53af', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/02aa623f-a023-419a-9b41-19a80d8e53af', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/02aa623f-a023-419a-9b41-19a80d8e53af', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T07:00:06Z', u'minDisk': 0, u'server': {u'id': u'a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'02aa623f-a023-419a-9b41-19a80d8e53af', u'metadata': {u'instance_uuid': u'a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T07:43:49Z', u'name': u'273-1375858801732-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/19a3fdb9-978d-47fb-b301-88af622ea194', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/19a3fdb9-978d-47fb-b301-88af622ea194', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/19a3fdb9-978d-47fb-b301-88af622ea194', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T07:00:04Z', u'minDisk': 0, u'server': {u'id': u'fb209de9-59d1-4e18-a951-4db2802ced23', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/fb209de9-59d1-4e18-a951-4db2802ced23', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/fb209de9-59d1-4e18-a951-4db2802ced23', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'19a3fdb9-978d-47fb-b301-88af622ea194', u'metadata': {u'instance_uuid': u'fb209de9-59d1-4e18-a951-4db2802ced23', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T07:43:43Z', u'name': u'272-1375858800056-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/be372779-a564-422b-8f02-b0f8fbf189c7', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/be372779-a564-422b-8f02-b0f8fbf189c7', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/be372779-a564-422b-8f02-b0f8fbf189c7', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T07:00:02Z', u'minDisk': 0, u'server': {u'id': u'39038bbd-524e-46e2-8058-1833eeb44e3a', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/39038bbd-524e-46e2-8058-1833eeb44e3a', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/39038bbd-524e-46e2-8058-1833eeb44e3a', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'be372779-a564-422b-8f02-b0f8fbf189c7', u'metadata': {u'instance_uuid': u'39038bbd-524e-46e2-8058-1833eeb44e3a', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T06:45:12Z', u'name': u'275-1375855202890-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/82e538a9-b767-4fda-8b69-3452a6fafdfc', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/82e538a9-b767-4fda-8b69-3452a6fafdfc', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/82e538a9-b767-4fda-8b69-3452a6fafdfc', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T06:00:04Z', u'minDisk': 0, u'server': {u'id': u'a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'82e538a9-b767-4fda-8b69-3452a6fafdfc', u'metadata': {u'instance_uuid': u'a82740cc-0bc8-4f76-81e2-3de2a1e551db', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T06:46:07Z', u'name': u'225-1375855200079-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/ecabf5fd-fc2a-48ed-9abd-00846a292322', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/ecabf5fd-fc2a-48ed-9abd-00846a292322', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/ecabf5fd-fc2a-48ed-9abd-00846a292322', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T06:00:02Z', u'minDisk': 0, u'server': {u'id': u'ce0a098f-ca02-41ee-9f78-b9625cf517cf', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/ce0a098f-ca02-41ee-9f78-b9625cf517cf', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/ce0a098f-ca02-41ee-9f78-b9625cf517cf', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'ecabf5fd-fc2a-48ed-9abd-00846a292322', u'metadata': {u'instance_uuid': u'ce0a098f-ca02-41ee-9f78-b9625cf517cf', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'e3b257fd-dc97-45a7-b134-668f469359fe', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T05:21:05Z', u'name': u'IMG_CENTOS6.3', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/2b46149b-6f07-4189-a5a3-ab119bc2001d', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/2b46149b-6f07-4189-a5a3-ab119bc2001d', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/2b46149b-6f07-4189-a5a3-ab119bc2001d', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T05:21:05Z', u'minDisk': 0, u'progress': 100, u'minRam': 0, u'id': u'2b46149b-6f07-4189-a5a3-ab119bc2001d', u'metadata': {}}, {u'status': u'ACTIVE', u'updated': u'2013-08-07T01:43:32Z', u'name': u'240-1375838760035-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/5c63b836-ebab-4185-abd5-7123e118e168', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/5c63b836-ebab-4185-abd5-7123e118e168', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/5c63b836-ebab-4185-abd5-7123e118e168', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-07T01:26:02Z', u'minDisk': 0, u'server': {u'id': u'2070c05c-591b-4962-b449-3607958b2f3d', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/2070c05c-591b-4962-b449-3607958b2f3d', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/2070c05c-591b-4962-b449-3607958b2f3d', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'5c63b836-ebab-4185-abd5-7123e118e168', u'metadata': {u'instance_uuid': u'2070c05c-591b-4962-b449-3607958b2f3d', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'vmware_image_version': u'1', u'vmware_adaptertype': u'lsiLogic', u'vmware_ostype': u'otherGuest', u'base_image_ref': u'b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-06T10:09:30Z', u'name': u'vm-windows_WINDOWS', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/1e3cb636-2053-45ff-9d98-ce2cb2578744', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/1e3cb636-2053-45ff-9d98-ce2cb2578744', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/1e3cb636-2053-45ff-9d98-ce2cb2578744', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-06T07:51:16Z', u'minDisk': 0, u'server': {u'id': u'1893e092-f644-4232-b83f-e8efecef88cd', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/1893e092-f644-4232-b83f-e8efecef88cd', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/1893e092-f644-4232-b83f-e8efecef88cd', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'1e3cb636-2053-45ff-9d98-ce2cb2578744', u'metadata': {u'instance_uuid': u'1893e092-f644-4232-b83f-e8efecef88cd', u'image_location': u'snapshot', u'image_state': u'available', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'ramdisk_id': None, u'kernel_id': None, u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'owner_id': u'e6442e3d73cc4a848d5acb44b618c144'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-05T11:13:46Z', u'name': u'221-1375700401337-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/bb319ed9-0687-4381-9908-22860059e883', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/bb319ed9-0687-4381-9908-22860059e883', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/bb319ed9-0687-4381-9908-22860059e883', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-05T11:00:03Z', u'minDisk': 0, u'server': {u'id': u'8bfcb4d6-bdc4-48cb-83a2-816a143e59d6', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/8bfcb4d6-bdc4-48cb-83a2-816a143e59d6', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/8bfcb4d6-bdc4-48cb-83a2-816a143e59d6', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'bb319ed9-0687-4381-9908-22860059e883', u'metadata': {u'instance_uuid': u'8bfcb4d6-bdc4-48cb-83a2-816a143e59d6', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'vmware_image_version': u'1', u'vmware_adaptertype': u'lsiLogic', u'vmware_ostype': u'otherGuest', u'base_image_ref': u'b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-05T07:45:46Z', u'name': u'window2003-img_WINDOWS', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/ad15ea0b-d5f3-4a17-ab6d-42605f53e99d', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/ad15ea0b-d5f3-4a17-ab6d-42605f53e99d', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/ad15ea0b-d5f3-4a17-ab6d-42605f53e99d', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-05T07:45:46Z', u'minDisk': 0, u'progress': 100, u'minRam': 0, u'id': u'ad15ea0b-d5f3-4a17-ab6d-42605f53e99d', u'metadata': {}}, {u'status': u'SAVING', u'updated': u'2013-08-02T05:20:03Z', u'name': u'184-1375420801869-STRASNAP', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/f2a0588d-8cc6-4383-824c-15f758980cef', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/f2a0588d-8cc6-4383-824c-15f758980cef', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/f2a0588d-8cc6-4383-824c-15f758980cef', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-02T05:20:03Z', u'minDisk': 0, u'server': {u'id': u'737ff503-4a3f-4120-a90c-7e77f5c99c6f', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/737ff503-4a3f-4120-a90c-7e77f5c99c6f', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/737ff503-4a3f-4120-a90c-7e77f5c99c6f', u'rel': u'bookmark'}]}, u'progress': 25, u'minRam': 0, u'id': u'f2a0588d-8cc6-4383-824c-15f758980cef', u'metadata': {u'image_type': u'snapshot', u'instance_uuid': u'737ff503-4a3f-4120-a90c-7e77f5c99c6f', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'base_image_ref': u'ef132735-2419-4984-8d12-2a769cdb5abd'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-01T08:52:42Z', u'name': u'liang001', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/f2493d68-1a89-40c7-ba81-9f7f3abc2bb5', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/f2493d68-1a89-40c7-ba81-9f7f3abc2bb5', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/f2493d68-1a89-40c7-ba81-9f7f3abc2bb5', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-01T08:39:15Z', u'minDisk': 0, u'server': {u'id': u'aa834928-d39a-4480-89ba-18be115ea9c7', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/servers/aa834928-d39a-4480-89ba-18be115ea9c7', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/servers/aa834928-d39a-4480-89ba-18be115ea9c7', u'rel': u'bookmark'}]}, u'progress': 100, u'minRam': 0, u'id': u'f2493d68-1a89-40c7-ba81-9f7f3abc2bb5', u'metadata': {u'instance_uuid': u'aa834928-d39a-4480-89ba-18be115ea9c7', u'user_id': u'88e552b352a243a4bb2cad526b95fdd3', u'image_type': u'snapshot', u'vmware_image_version': u'1', u'vmware_adaptertype': u'lsiLogic', u'vmware_ostype': u'otherGuest', u'base_image_ref': u'b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5'}}, {u'status': u'ACTIVE', u'updated': u'2013-08-01T08:07:10Z', u'name': u'vmdk-centos_LINUX', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-01T08:07:10Z', u'minDisk': 0, u'progress': 100, u'minRam': 0, u'id': u'b5c0fc95-c3b6-4db1-8ddc-a6bff141bde5', u'metadata': {}}, {u'status': u'ACTIVE', u'updated': u'2013-08-01T04:16:44Z', u'name': u'img_centos_centos6.2', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/e3b257fd-dc97-45a7-b134-668f469359fe', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/e3b257fd-dc97-45a7-b134-668f469359fe', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/e3b257fd-dc97-45a7-b134-668f469359fe', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-01T04:16:44Z', u'minDisk': 0, u'progress': 100, u'minRam': 0, u'id': u'e3b257fd-dc97-45a7-b134-668f469359fe', u'metadata': {}}, {u'status': u'ACTIVE', u'updated': u'2013-08-01T03:01:23Z', u'name': u'img_windows_windows2003', u'links': [{u'href': u'http://192.168.0.55:8774/v2/e6442e3d73cc4a848d5acb44b618c144/images/ef132735-2419-4984-8d12-2a769cdb5abd', u'rel': u'self'}, {u'href': u'http://192.168.0.55:8774/e6442e3d73cc4a848d5acb44b618c144/images/ef132735-2419-4984-8d12-2a769cdb5abd', u'rel': u'bookmark'}, {u'href': u'http://192.168.0.55:9292/e6442e3d73cc4a848d5acb44b618c144/images/ef132735-2419-4984-8d12-2a769cdb5abd', u'type': u'application/vnd.openstack.image', u'rel': u'alternate'}], u'created': u'2013-08-01T03:01:23Z', u'minDisk': 0, u'progress': 100, u'minRam': 0, u'id': u'ef132735-2419-4984-8d12-2a769cdb5abd', u'metadata': {}}]}}
[2013-08-07 19:25:16,285](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:25:16] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 19:28:57,276](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 19:29:00,508](DEBUG)__main__ : ********************get_images********************
[2013-08-07 19:29:06,488](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:29:06] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 19:36:18,687](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 19:36:21,668](DEBUG)__main__ : ********************  get_images  ********************
[2013-08-07 19:36:21,973](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:36:21] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 19:36:34,943](DEBUG)__main__ : ********************  get_flavors  ********************
[2013-08-07 19:36:35,003](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:36:35] "GET /get_flavors HTTP/1.1" 200 -
[2013-08-07 19:54:07,002](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 19:54:11,761](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 19:54:11,761](DEBUG)__main__ : token: 4424558583534c2e8ff4e4bed081d6fe, nova: /v2/e6442e3d73cc4a848d5acb44b618c144
[2013-08-07 19:54:11,762](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 19:54:11,763](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:54:11] "GET / HTTP/1.1" 200 -
[2013-08-07 19:55:00,019](DEBUG)__main__ : ********************  get_images  ********************
[2013-08-07 19:55:00,337](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 19:55:00] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 21:05:43,380](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:05:50,184](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 21:05:50,184](DEBUG)__main__ : token: 91a9df124b2b4baf98c0ce1488450558, nova: /v2/e6442e3d73cc4a848d5acb44b618c144
[2013-08-07 21:05:50,185](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 21:05:50,186](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:05:50] "GET / HTTP/1.1" 200 -
[2013-08-07 21:08:30,542](ERROR)__main__ : Exception on /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: check_server() got an unexpected keyword argument 'type'
[2013-08-07 21:08:30,559](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:08:30] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 500 -
[2013-08-07 21:09:16,434](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:09:19,592](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 21:09:19,593](DEBUG)amqp : Open OK!
[2013-08-07 21:09:19,593](DEBUG)amqp : using channel_id: 1
[2013-08-07 21:09:19,594](DEBUG)amqp : Channel open
[2013-08-07 21:09:19,596](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:09:19] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:10:18,934](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:10:23,480](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 21:10:23,481](DEBUG)amqp : Open OK!
[2013-08-07 21:10:23,481](DEBUG)amqp : using channel_id: 1
[2013-08-07 21:10:23,482](DEBUG)amqp : Channel open
[2013-08-07 21:10:23,492](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:10:23] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:11:08,177](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:11:08] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:13:19,402](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:13:23,914](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 21:13:23,915](DEBUG)amqp : Open OK!
[2013-08-07 21:13:23,916](DEBUG)amqp : using channel_id: 1
[2013-08-07 21:13:23,916](DEBUG)amqp : Channel open
[2013-08-07 21:13:23,920](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:13:23] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:14:08,346](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:14:08] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:14:48,028](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:14:48] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:15:07,461](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 21:15:07,462](DEBUG)__main__ : token: e738eff197c14779986336fc979b7339, nova: /v2/e6442e3d73cc4a848d5acb44b618c144
[2013-08-07 21:15:07,463](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-07 21:15:07,463](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:15:07] "GET / HTTP/1.1" 200 -
[2013-08-07 21:15:10,150](DEBUG)__main__ : ********************  get_images  ********************
[2013-08-07 21:15:10,311](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:15:10] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 21:18:42,913](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:18:42] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:18:44,150](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:18:44] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:18:45,850](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:18:45] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 21:27:14,228](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:27:23,256](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images()
  File "/opt/app/ephem_flask/utils.py", line 132, in get_images
    LOG.debug("*"*20 + "  get_images  " + "*"*20)
NameError: global name 'LOG' is not defined
[2013-08-07 21:27:23,270](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:27:23] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:27:26,190](DEBUG)__main__ : ********************  get_flavors  ********************
[2013-08-07 21:27:26,243](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:27:26] "GET /get_flavors HTTP/1.1" 200 -
[2013-08-07 21:27:35,764](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images()
  File "/opt/app/ephem_flask/utils.py", line 132, in get_images
    LOG.debug("*"*20 + "  get_images  " + "*"*20)
NameError: global name 'LOG' is not defined
[2013-08-07 21:27:35,765](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:27:35] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:28:09,779](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:28:12,370](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images()
  File "/opt/app/ephem_flask/utils.py", line 132, in get_images
    headers = {"X-Auth-Token": g.token, "Content-type": "application/json"}
NameError: global name 'g' is not defined
[2013-08-07 21:28:12,384](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:28:12] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:30:01,687](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:30:04,885](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images(g.token, g.nova_path)
  File "/opt/app/ephem_flask/utils.py", line 134, in get_images
    "url": app.config['NOVA_IP'],
NameError: global name 'app' is not defined
[2013-08-07 21:30:04,899](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:30:04] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:30:37,189](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:30:38,801](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images(g.token, g.nova_path)
  File "/opt/app/ephem_flask/utils.py", line 134, in get_images
    "url": config.NOVA_IP,
NameError: global name 'config' is not defined
[2013-08-07 21:30:38,809](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:30:38] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:31:00,029](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:31:01,881](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images(g.token, g.nova_path)
  File "/opt/app/ephem_flask/utils.py", line 137, in get_images
    "params": urllib.urlencode({}),
NameError: global name 'urllib' is not defined
[2013-08-07 21:31:01,889](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:31:01] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:31:15,291](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:31:16,702](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 151, in get_images
    rsp = utils.get_images(g.token, g.nova_path)
  File "/opt/app/ephem_flask/utils.py", line 146, in get_images
    rreq = json.dumps(req)
NameError: global name 'json' is not defined
[2013-08-07 21:31:16,716](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:31:16] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 21:31:30,872](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 21:31:32,938](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 21:31:32] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 22:38:14,376](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:38:17,998](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "iaasapi.py", line 38, in before_request
    g.token, nova_url = get_token()
NameError: global name 'get_token' is not defined
[2013-08-07 22:38:18,014](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:38:18] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 22:40:30,295](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:40:32,312](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "iaasapi.py", line 38, in before_request
    g.iaas = utils.DoAsIAAS()
  File "/opt/app/ephem_flask/utils.py", line 40, in __init__
    self.token, nova_url = get_token()
NameError: global name 'get_token' is not defined
[2013-08-07 22:40:32,327](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:40:32] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 22:40:54,667](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:40:56,924](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "iaasapi.py", line 38, in before_request
    g.iaas = utils.DoAsIAAS()
  File "/opt/app/ephem_flask/utils.py", line 40, in __init__
    self.token, nova_url = self.get_token()
  File "/opt/app/ephem_flask/utils.py", line 80, in get_token
    rsp = json.loads(knock_iaas(rreq))
NameError: global name 'knock_iaas' is not defined
[2013-08-07 22:40:56,936](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:40:56] "GET /get_images HTTP/1.1" 500 -
[2013-08-07 22:41:44,555](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:42:04,403](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:42:04] "GET /get_images HTTP/1.1" 200 -
[2013-08-07 22:44:45,885](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:44:45] "GET /get_flavors HTTP/1.1" 404 -
[2013-08-07 22:45:31,450](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:45:33,842](ERROR)__main__ : Exception on /get_flavors [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 75, in get_flavors
    rsp = g.iaas.get_flavors()
  File "/opt/app/ephem_flask/utils.py", line 492, in get_flavors
    rsp_from_iaas = json.loads(iaas_func(rreq))
NameError: global name 'iaas_func' is not defined
[2013-08-07 22:45:33,850](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:45:33] "GET /get_flavors HTTP/1.1" 500 -
[2013-08-07 22:45:57,388](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:45:59,066](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:45:59] "GET /get_flavors HTTP/1.1" 200 -
[2013-08-07 22:49:35,622](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:49:52,820](ERROR)__main__ : Exception on /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "iaasapi.py", line 60, in check_server
    token = g.token
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'token'
[2013-08-07 22:49:52,851](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:49:52] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 500 -
[2013-08-07 22:50:23,150](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 22:50:24,656](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 22:50:24,657](DEBUG)amqp : Open OK!
[2013-08-07 22:50:24,658](DEBUG)amqp : using channel_id: 1
[2013-08-07 22:50:24,659](DEBUG)amqp : Channel open
[2013-08-07 22:50:24,661](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 22:50:24] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 23:02:31,189](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 23:02:35,100](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 23:02:35,102](DEBUG)amqp : Open OK!
[2013-08-07 23:02:35,103](DEBUG)amqp : using channel_id: 1
[2013-08-07 23:02:35,104](DEBUG)amqp : Channel open
[2013-08-07 23:02:35,107](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 23:02:35] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 23:05:40,939](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 23:05:47,018](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 23:05:47,019](DEBUG)amqp : Open OK!
[2013-08-07 23:05:47,019](DEBUG)amqp : using channel_id: 1
[2013-08-07 23:05:47,019](DEBUG)amqp : Channel open
[2013-08-07 23:05:47,022](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 23:05:47] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 23:52:10,141](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 23:52:13,562](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 23:52:13,563](DEBUG)amqp : Open OK!
[2013-08-07 23:52:13,563](DEBUG)amqp : using channel_id: 1
[2013-08-07 23:52:13,564](DEBUG)amqp : Channel open
[2013-08-07 23:52:13,567](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 23:52:13] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-07 23:53:16,750](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-07 23:53:19,303](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-07 23:53:19,304](DEBUG)amqp : Open OK!
[2013-08-07 23:53:19,304](DEBUG)amqp : using channel_id: 1
[2013-08-07 23:53:19,305](DEBUG)amqp : Channel open
[2013-08-07 23:53:19,307](INFO)werkzeug : 127.0.0.1 - - [07/Aug/2013 23:53:19] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-08 00:15:01,129](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 00:15:03,688](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-08 00:15:03,689](DEBUG)amqp : Open OK!
[2013-08-08 00:15:03,689](DEBUG)amqp : using channel_id: 1
[2013-08-08 00:15:03,690](DEBUG)amqp : Channel open
[2013-08-08 00:15:03,694](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 00:15:03] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-08 00:19:23,091](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 00:19:29,943](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-08 00:19:29,944](DEBUG)amqp : Open OK!
[2013-08-08 00:19:29,944](DEBUG)amqp : using channel_id: 1
[2013-08-08 00:19:29,945](DEBUG)amqp : Channel open
[2013-08-08 00:19:29,950](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 00:19:29] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-08 00:38:30,213](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 00:38:38,001](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 00:38:43,116](DEBUG)amqp : Start from server, version: 0.9, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 VMware, Inc.', u'capabilities': {u'exchange_exchange_bindings': True, u'consumer_cancel_notify': True, u'publisher_confirms': True, u'basic.nack': True}, u'platform': u'Erlang/OTP', u'version': u'3.1.3'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
[2013-08-08 00:38:43,117](DEBUG)amqp : Open OK!
[2013-08-08 00:38:43,117](DEBUG)amqp : using channel_id: 1
[2013-08-08 00:38:43,118](DEBUG)amqp : Channel open
[2013-08-08 00:38:43,120](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 00:38:43] "GET /check_server/a36ff49a-1ce5-4fb0-877a-0b07115b1488/check_status HTTP/1.1" 200 -
[2013-08-08 00:49:54,739](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 00:50:00,964](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 00:50:00] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 00:52:55,483](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 00:52:57,828](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 00:52:57] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:17:09,997](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:17:18,037](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-08 21:17:18,056](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 45, in index
    {'token': g.token, 'nova': g.nova_path})
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'token'
[2013-08-08 21:17:18,091](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:17:18] "GET / HTTP/1.1" 500 -
[2013-08-08 21:17:18,358](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:17:18] "GET /favicon.ico HTTP/1.1" 404 -
[2013-08-08 21:17:18,555](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:17:18] "GET /favicon.ico HTTP/1.1" 404 -
[2013-08-08 21:17:20,748](DEBUG)__main__ : ++++++++++++++++++++
[2013-08-08 21:17:20,749](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 45, in index
    {'token': g.token, 'nova': g.nova_path})
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'token'
[2013-08-08 21:17:20,750](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:17:20] "GET / HTTP/1.1" 500 -
[2013-08-08 21:18:02,854](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:18:04,587](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:18:04] "GET / HTTP/1.1" 200 -
[2013-08-08 21:18:11,689](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:18:11] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:27:34,782](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:27:37,312](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 83, in get_images
    rsp = g.iaas.get_images()
TypeError: rsp_deco() takes no arguments (1 given)
[2013-08-08 21:27:37,326](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:27:37] "GET /get_images HTTP/1.1" 500 -
[2013-08-08 21:29:44,649](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:29:46,236](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 792, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 853, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'dict' object is not callable
[2013-08-08 21:29:46,267](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:29:46] "GET /get_images HTTP/1.1" 500 -
[2013-08-08 21:31:15,219](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:31:17,202](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:31:17] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:38:09,626](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:38:12,197](ERROR)__main__ : Exception on /get_images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/ephem_flask/decorator.py", line 21, in rsp_deco
    self.fin_rsp['data'] = data
NameError: global name 'data' is not defined
[2013-08-08 21:38:12,210](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:38:12] "GET /get_images HTTP/1.1" 500 -
[2013-08-08 21:38:33,217](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:38:45,006](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:38:45] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:38:48,694](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:38:48] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:41:45,466](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:42:54,144](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:42:57,197](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:42:57] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:43:00,507](ERROR)__main__ : Exception on /get_flavors [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 792, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 853, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'dict' object is not callable
[2013-08-08 21:43:00,512](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:43:00] "GET /get_flavors HTTP/1.1" 500 -
[2013-08-08 21:43:17,855](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:43:19,675](ERROR)__main__ : Exception on /get_flavors [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 792, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 853, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'dict' object is not callable
[2013-08-08 21:43:19,679](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:43:19] "GET /get_flavors HTTP/1.1" 500 -
[2013-08-08 21:44:03,667](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:44:05,391](ERROR)__main__ : Exception on /get_flavors [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 792, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 853, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'dict' object is not callable
[2013-08-08 21:44:05,395](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:44:05] "GET /get_flavors HTTP/1.1" 500 -
[2013-08-08 21:44:29,364](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:44:29] "GET /get_images HTTP/1.1" 200 -
[2013-08-08 21:46:11,836](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:46:15,907](ERROR)__main__ : Exception on /get_flavors [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 792, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 853, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'dict' object is not callable
[2013-08-08 21:46:15,913](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:46:15] "GET /get_flavors HTTP/1.1" 500 -
[2013-08-08 21:47:39,373](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 21:47:41,742](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 21:47:41] "GET /get_flavors HTTP/1.1" 200 -
[2013-08-08 22:37:57,566](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 22:38:00,208](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:38:00] "GET /get_flavors HTTP/1.1" 200 -
[2013-08-08 22:38:02,550](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:38:02] "GET /get_flavors HTTP/1.1" 200 -
[2013-08-08 22:38:06,616](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:38:06] "GET /get_quota/ HTTP/1.1" 404 -
[2013-08-08 22:38:12,716](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:38:12] "GET /get_quotas/ HTTP/1.1" 404 -
[2013-08-08 22:41:01,350](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:41:01] "GET /get_quotas/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 404 -
[2013-08-08 22:41:06,250](ERROR)__main__ : Exception on /get_quota/e6442e3d73cc4a848d5acb44b618c144 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: get_quota_rsp_deco() takes no arguments (1 given)
[2013-08-08 22:41:06,252](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:41:06] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 500 -
[2013-08-08 22:41:56,847](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 22:41:58,854](ERROR)__main__ : Exception on /get_quota/e6442e3d73cc4a848d5acb44b618c144 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/ephem_flask/decorator.py", line 64, in get_quota_rsp_deco
    iaas_quota = rsp['data']['quota_set']
TypeError: string indices must be integers, not str
[2013-08-08 22:41:58,870](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:41:58] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 500 -
[2013-08-08 22:42:26,327](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 22:42:28,016](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 22:42:28] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-08 23:35:25,991](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:35:30,152](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 47, in index
    print g.request
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'request'
[2013-08-08 23:35:30,161](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:35:30] "GET / HTTP/1.1" 500 -
[2013-08-08 23:37:22,801](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:37:25,508](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:37:25] "GET / HTTP/1.1" 200 -
[2013-08-08 23:38:02,853](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:38:05,881](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:38:05] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-08 23:38:31,757](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:38:33,719](ERROR)__main__ : Exception on /get_quota/e6442e3d73cc4a848d5acb44b618c144 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/ephem_flask/decorator.py", line 58, in get_quota_rsp_deco
    rsp = func(tenant_id)
  File "app.py", line 75, in get_quota
    print request.params
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'params'
[2013-08-08 23:38:33,731](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:38:33] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 500 -
[2013-08-08 23:41:51,346](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:41:53,639](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:41:53] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-08 23:54:16,679](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:54:16] "GET / HTTP/1.1" 200 -
[2013-08-08 23:54:40,645](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:54:40] "GET / HTTP/1.1" 200 -
[2013-08-08 23:55:17,231](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:55:21,159](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:55:21] "GET / HTTP/1.1" 200 -
[2013-08-08 23:55:29,122](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:55:29] "GET / HTTP/1.1" 200 -
[2013-08-08 23:56:11,457](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:56:11] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-08 23:56:38,820](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:56:48,903](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:56:50,558](ERROR)__main__ : Exception on /get_quota/e6442e3d73cc4a848d5acb44b618c144 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/ephem_flask/decorator.py", line 58, in get_quota_rsp_deco
    rsp = func(tenant_id)
  File "app.py", line 76, in get_quota
    print request.headers["Ad"]
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 1269, in __getitem__
    return _unicodify_header_value(self.environ['HTTP_' + key])
KeyError: 'HTTP_AD'
[2013-08-08 23:56:50,597](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:56:50] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 500 -
[2013-08-08 23:57:30,487](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:57:33,497](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:57:33] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-08 23:58:25,538](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:58:28,243](ERROR)__main__ : Exception on /get_quota/e6442e3d73cc4a848d5acb44b618c144 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/ephem_flask/decorator.py", line 58, in get_quota_rsp_deco
    rsp = func(tenant_id)
  File "app.py", line 76, in get_quota
    print request.header
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'header'
[2013-08-08 23:58:28,257](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:58:28] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 500 -
[2013-08-08 23:58:51,756](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-08 23:58:54,018](INFO)werkzeug : 127.0.0.1 - - [08/Aug/2013 23:58:54] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-09 00:12:29,590](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:12:29] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-09 00:13:20,962](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:13:23,773](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:13:23] "GET /get_quota/e6442e3d73cc4a848d5acb44b618c144 HTTP/1.1" 200 -
[2013-08-09 00:24:18,259](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:24:52,115](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:24:52] "POST /get_quota/ HTTP/1.1" 405 -
[2013-08-09 00:26:09,938](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:26:12,926](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:26:12] "POST /get_quota/ HTTP/1.1" 404 -
[2013-08-09 00:33:40,166](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:33:50,039](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:33:50] "POST / HTTP/1.1" 405 -
[2013-08-09 00:34:01,642](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 47, in index
    print request.params
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'params'
[2013-08-09 00:34:01,645](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:34:01] "GET / HTTP/1.1" 500 -
[2013-08-09 00:34:44,939](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:34:44] "POST / HTTP/1.1" 405 -
[2013-08-09 00:35:01,327](ERROR)__main__ : Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 47, in index
    print request.params
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'params'
[2013-08-09 00:35:01,330](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:35:01] "GET / HTTP/1.1" 500 -
[2013-08-09 00:35:04,840](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:35:04] "POSR / HTTP/1.1" 405 -
[2013-08-09 00:35:07,622](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:35:07] "POST / HTTP/1.1" 405 -
[2013-08-09 00:35:24,317](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:35:24] "POST / HTTP/1.1" 405 -
[2013-08-09 00:37:51,492](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:37:55,293](ERROR)__main__ : Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 47, in index
    print request.params
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'params'
[2013-08-09 00:37:55,306](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:37:55] "POST / HTTP/1.1" 500 -
[2013-08-09 00:38:21,364](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:38:23,185](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:38:23] "POST / HTTP/1.1" 200 -
[2013-08-09 00:38:48,340](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:38:51,512](ERROR)__main__ : Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 47, in index
    print request.param
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'param'
[2013-08-09 00:38:51,525](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:38:51] "POST / HTTP/1.1" 500 -
[2013-08-09 00:39:51,437](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:39:53,862](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:39:53] "POST / HTTP/1.1" 200 -
[2013-08-09 00:47:46,759](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 00:47:51,241](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 00:47:51] "POST / HTTP/1.1" 404 -
[2013-08-09 01:06:19,542](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:06:19] "POST / HTTP/1.1" 404 -
[2013-08-09 01:07:27,995](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 01:07:32,419](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:07:32] "POST / HTTP/1.1" 404 -
[2013-08-09 01:07:49,150](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:07:49] "POST / HTTP/1.1" 404 -
[2013-08-09 01:30:18,942](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:30:18] "POST /aa/ HTTP/1.1" 404 -
[2013-08-09 01:32:10,710](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 01:32:13,057](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:32:13] "POST /aa/ HTTP/1.1" 404 -
[2013-08-09 01:32:17,863](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:32:17] "POST / HTTP/1.1" 200 -
[2013-08-09 01:32:40,159](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 01:32:41,813](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:32:41] "POST / HTTP/1.1" 200 -
[2013-08-09 01:34:40,090](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 01:34:42,063](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:34:42] "POST / HTTP/1.1" 400 -
[2013-08-09 01:36:09,245](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 01:36:11,348](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:36:11] "POST / HTTP/1.1" 200 -
[2013-08-09 01:54:49,077](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 01:54:51,080](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:54:51] "POST / HTTP/1.1" 405 -
[2013-08-09 01:54:58,495](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 01:54:58] "POST / HTTP/1.1" 405 -
[2013-08-09 02:01:52,133](INFO)werkzeug :  * Running on http://0.0.0.0:8080/
[2013-08-09 02:02:31,964](ERROR)__main__ : Exception on /get_quota/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: get_quota_rsp_deco() takes exactly 1 argument (0 given)
[2013-08-09 02:02:31,977](INFO)werkzeug : 127.0.0.1 - - [09/Aug/2013 02:02:31] "POST /get_quota/ HTTP/1.1" 500 -
